TEST_VALUE:
  name: cookie
MONGODB_CONFIG:
  name: "mongodb_dev"                         # 自定义数据库连接名称
  type: mongodb                               # 数据库类型
  url: "mongodb://localhost:27017"            # 数据库连接地址
  username: "chencs"                          # 数据库连接用户名
  password: "123456"                          # 数据库连接密码
  database: "fast_gateway_test"               # 数据库名
  entities: "mongo"                           # 自定义加载类型
  logging: false                              # 数据库打印日志
  synchronize: true                           # 是否开启同步数据表功能
MYSQL_CONFIG: 
  name: "mysql_dev"
  type: mysql
  host: "127.0.0.1"
  port: 3306
  username: "chencs"
  password: "123456"
  database: "material_test"
  entities: "mysql"
  logging: true
  synchronize: true